//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Cus_MES_To_MidTable
    {
        public long ID { get; set; }
        public string BillNo { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public string Auditor { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public string RowNo { get; set; }
        public string ProCode { get; set; }
        public string ProName { get; set; }
        public string Version { get; set; }
        public string Batch { get; set; }
        public string Qty { get; set; }
        public string Units { get; set; }
        public string ReactorCode { get; set; }
        public string ValType { get; set; }
        public string ValHome { get; set; }
        public Nullable<System.DateTime> ValDate { get; set; }
        public Nullable<System.DateTime> ProDate { get; set; }
        public string FinishQty { get; set; }
        public Nullable<System.DateTime> FinishValDate { get; set; }
        public Nullable<System.DateTime> FinishProDate { get; set; }
        public string PalletizerArea { get; set; }
        public string PalletizerCode { get; set; }
        public Nullable<System.DateTime> PalletizerStartTime { get; set; }
        public Nullable<System.DateTime> PalletizerEndTime { get; set; }
        public string PalletizerStatus { get; set; }
        public Nullable<long> iEESID { get; set; }
        public Nullable<System.DateTime> dDateTime { get; set; }
        public Nullable<int> iDetectionStatus { get; set; }
    }
}
