//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5.manger.Models
{
    public partial class bumen
    {
        public int ID { get; set; }
        public string bumenName { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int num { get; set; }
        public string states { get; set; }
    }
}