//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5.manger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checking
    {
        public int id { get; set; }
        public string name { get; set; }
        public string danhao { get; set; }
        public string style { get; set; }
        public string didian { get; set; }
        public string danjia { get; set; }
        public string shulu { get; set; }
    }
}
