//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5.manger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public string customerid { get; set; }
        public string companyname { get; set; }
        public string connectname { get; set; }
        public string addresss { get; set; }
        public string zipcode { get; set; }
        public Nullable<int> telephone { get; set; }
    }
}
