//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5.manger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class department
    {
        public int ID { get; set; }
        public string departmentName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> num { get; set; }
        public string states { get; set; }
    }
}
