//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5.manger.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mangerEntities : DbContext
    {
        public mangerEntities()
            : base("name=mangerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<staffInfo> staffInfo { get; set; }
        public virtual DbSet<userChecke> userChecke { get; set; }
        public virtual DbSet<department> department { get; set; }
        public virtual DbSet<userinfo> userinfo { get; set; }
        public virtual DbSet<Training> Training { get; set; }
    }
}
