//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5.manger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class staffInfo
    {
        public int empId { get; set; }
        public string empName { get; set; }
        public string empPosition { get; set; }
        public Nullable<int> empHrId { get; set; }
        public System.DateTime empInDate { get; set; }
        public decimal empSalary { get; set; }
        public Nullable<decimal> empBonus { get; set; }
        public Nullable<int> deptId { get; set; }
    }
}
