//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5.manger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userinfo
    {
        public int userID { get; set; }
        public string userSex { get; set; }
        public Nullable<int> userPhone { get; set; }
        public string userNum { get; set; }
        public string usermingzu { get; set; }
        public string userAderrs { get; set; }
        public string userPhot { get; set; }
    }
}
