//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5.manger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userChecke
    {
        public int userID { get; set; }
        public string userName { get; set; }
        public string userLog { get; set; }
        public string userPwd { get; set; }
        public string userType { get; set; }
    }
}
